---
title: "Johns Hopkins Covid-19 Data Analysis"
date: "06/20/2023"
output:
  rmdformats::readthedown:
    highlight: kate
---
## Setup: 
```{r}
suppressPackageStartupMessages({
    library(tidyverse)
    library(lubridate)
    library(ggplot2)
    library(leaflet)
    library(gganimate)
    library(gifski)
    library(maps)
  library(EpiEstim)
})
confirmed_us <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")
confirmed_global <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
death_us <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_US.csv")
death_global <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")

options(scipen = 100)
```

## Cleaning the data:

```{r Initial Cleaning and Case Rates}
confirmed_global$Key <- paste0(confirmed_global$Province.State, confirmed_global$Country.Region)
death_global$Key <- paste0(death_global$Province.State,death_global$Country.Region)

us_data <- left_join(confirmed_us, death_us, by = "Combined_Key", suffix = c(".case",".death"))
global_data <- left_join(confirmed_global, death_global, by = "Key", suffix = c(".case",".death"))

us_data$case_sum <- us_data$X3.9.23.case
# us_data$case_sum[us_data$case_sum>100000] <- 100000
us_data$case_rate <- (us_data$case_sum/us_data$Population)*100000
us_data$case_rate <- ifelse(us_data$case_rate==0 | is.nan(us_data$case_rate) | us_data$case_rate==Inf, yes = 0, no = us_data$case_rate)
```

```{r Map Data}
us_map <- map_data("county")
us_map$Combined_Key <- toupper(paste(us_map$subregion, us_map$region, "US", sep = ", "))
us_data$Combined_Key <- toupper(us_data$Combined_Key)


us_map <- left_join(us_map, us_data, by = "Combined_Key")

us_map$case_rate2 <- us_map$case_rate
us_map$case_rate2[us_map$case_rate2>100000] <- 100000
```

```{r Tarrant Data}
tarrant_data <- us_data[us_data$Admin2.case=="Tarrant",]

tarrant_cases <- tarrant_data[,grepl(".case",colnames(tarrant_data))]
tarrant_cases <- pivot_longer(tarrant_cases,cols = c(11:1153))
tarrant_cases$Date_final <- gsub("X|.case","",tarrant_cases$name)
tarrant_cases$Date_final<- as.Date(tarrant_cases$Date_final, format = "%m.%d.%y")

tarrant_deaths <- tarrant_data[,grepl(".death",colnames(tarrant_data))]
tarrant_deaths <- pivot_longer(tarrant_deaths,cols = c(11:1153))
tarrant_deaths$Date_final <- gsub("X|.death","",tarrant_deaths$name)
tarrant_deaths$Date_final <- as.Date(tarrant_deaths$Date_final, format = "%m.%d.%y")
```

```{r SIR Chart Data}
global_case_long <- pivot_longer(confirmed_global,cols = c(5:1147))
global_case_long$date_final <- as.Date(gsub("X","",global_case_long$name),format = "%m.%d.%y")
global_death_long <- pivot_longer(death_global, cols = c(5:1147))
global_death_long$date_final <- as.Date(gsub("X","",global_death_long$name),format = "%m.%d.%y")
total_data_comb <- as.data.frame(matrix(data = NA, nrow = 1143, ncol = 5))
colnames(total_data_comb) <- c("final_date","active","deaths","recovered","uninfected")
total_data_comb$final_date <- tarrant_cases$Date_final



us_case_long <- us_data[,grepl(".case",colnames(us_data))]
us_case_long <- pivot_longer(us_case_long,cols = c(11:1153))
us_case_long$Date_final <- gsub("X|.case","",us_case_long$name)
us_case_long$Date_final <- as.Date(us_case_long$Date_final, format = "%m.%d.%y")

us_deaths_long <- us_data[,grepl(".death",colnames(us_data))]
us_deaths_long <- pivot_longer(us_deaths_long,cols = c(11:1153))
us_deaths_long$Date_final <- gsub("X|.death","",us_deaths_long$name)
us_deaths_long$Date_final <- as.Date(us_deaths_long$Date_final, format = "%m.%d.%y")

us_data_comb <- as.data.frame(matrix(data = NA, nrow = 1143, ncol = 5))
colnames(us_data_comb) <- c("final_date","active","deaths","recovered","uninfected")
us_data_comb$final_date <- tarrant_cases$Date_final

system.time({
  for(i in 1:nrow(us_data_comb)){
 us_data_comb$deaths[i]<- sum(us_deaths_long$value[us_deaths_long$Date_final==us_data_comb$final_date[i]])
 us_data_comb$recovered[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]-30])
 us_data_comb$active[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]])-us_data_comb$recovered[i]
 us_data_comb$cases[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]])
}
})

system.time({
  us_deaths <- numeric(nrow(us_data_comb))
  us_recovered <- numeric(nrow(us_data_comb))
  us_active <- numeric(nrow(us_data_comb))
  us_cases <- numeric(nrow(us_data_comb))
  for(i in 1:nrow(us_data_comb)){
 us_deaths[i]<- sum(us_deaths_long$value[us_deaths_long$Date_final==us_data_comb$final_date[i]])
 us_recovered[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]-30])
 us_active[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]])-us_data_comb$recovered[i]
 us_cases[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]])
}
})

system.time({
  us_deaths <- numeric(nrow(us_data_comb))
  for(i in 1:nrow(us_data_comb)){
 us_deaths[i]<- sum(us_deaths_long$value[us_deaths_long$Date_final==us_data_comb$final_date[i]])
}
})

system.time({
  us_recovered <- numeric(nrow(us_data_comb))
  for(i in 1:nrow(us_data_comb)){
 us_recovered[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]-30])
}
})

system.time({
  us_active <- numeric(nrow(us_data_comb))
  for(i in 1:nrow(us_data_comb)){
 us_active[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]])-us_data_comb$recovered[i]
}
})

system.time({
  us_cases <- numeric(nrow(us_data_comb))
  for(i in 1:nrow(us_data_comb)){
 us_cases[i] <- sum(us_case_long$value[us_case_long$Date_final==us_data_comb$final_date[i]])
}
})

### This is half the time
system.time({
  us_long_val <- us_case_long$value
  us_long_val2 <- us_deaths_long$value
  us_long_date <- us_case_long$Date_final
  dates <- us_data_comb$final_date
  
  us_cases <- numeric(nrow(us_data_comb))
  us_active <- numeric(nrow(us_data_comb))
  us_recovered <- numeric(nrow(us_data_comb))
  us_deaths <- numeric(nrow(us_data_comb))
  
  for(i in 1:nrow(us_data_comb)){
    ndx <- us_long_date==dates[i]
 us_cases[i] <- sum(us_long_val[ndx])
 us_deaths[i]<- sum(us_long_val2[ndx])
  }
  for(i in 1:nrow(us_data_comb)){
    ndx <- us_long_date==dates[i]-30
  us_recovered[i] <- sum(us_long_val[ndx])
  }
  
  us_active <- us_cases-us_recovered
  us_data_comb$active <- us_active
  us_data_comb$deaths <- us_deaths
  us_data_comb$recovered <- us_recovered
  us_data_comb$cases <- us_cases
})

us_data_comb$uninfected <- 331900000

```

```{r US Rt Data}
us_data_comb$new_cases <- NA
for(i in 1:nrow(us_data_comb)){
  if(i ==1){
    us_data_comb$new_cases[i] <- 0
  } else {
    us_data_comb$new_cases[i] <- us_data_comb$cases[i]-us_data_comb$cases[i-1] 
  }
}
us_data_comb$new_cases <- ifelse(us_data_comb$new_cases < 0 , yes = 0 , no = us_data_comb$new_cases)
Rt_data <- estimate_R(us_data_comb$new_cases[90:nrow(us_data_comb)], method = "parametric_si", config = make_config(list(mean_si = 5.2, std_si = 5.1)))$R

missing_Rt <- Rt_data[1:7,]
missing_Rt[,c(1:11)] <- NA
Rt_data <- rbind(missing_Rt, Rt_data)

us_data_comb_Rt <- cbind(us_data_comb[90:nrow(us_data_comb),],Rt_data)
```


## Visualization: 

```{r Map1}

map1 <- ggplot(data = us_map, aes(x = long, y = lat, group = group, fill = case_rate2))+
  geom_polygon(color = "white", linewidth = .001)+
  coord_quickmap()+
  # scale_fill_gradient2(low = "#ffeda0",mid = "#feb24c", high = "#f03b20", midpoint = mean(us_data$case_rate)/3)
  scale_fill_viridis_c(option = "rocket", direction = -1, name = "Cases per 100K", labels = c("0","25,000","50,000","75,000","100,000+"))+
  theme_void()+
  ggtitle("US Counties by Cases per 100K population")+
  theme(plot.title = element_text(hjust = 0.5))

map1
```

```{r Tarrant Cases}
key_date <- c("2020-03-12","2020-10-11","2021-07-14","2021-12-08","2022-06-02","2022-12-02")
tarrant_key_dates <- data.frame(key_date)
tarrant_key_dates$key_date <- as.Date(tarrant_key_dates$key_date,format = "%Y-%m-%d")
tarrant_key_dates$Count <- tarrant_cases$value[tarrant_cases$Date_final %in% tarrant_key_dates$key_date]

chart1 <- suppressWarnings({ ggplot()+
  geom_line(data = tarrant_cases,aes(x = Date_final , y = value, color = "Cases"), size = 1)+
  geom_line(data = tarrant_deaths,aes(x = Date_final, y = value, color = "Deaths"), size = 1)+
  geom_point(data = tarrant_key_dates, aes(x = key_date, y = Count), color = "black", size = 3)+
  geom_text(data = tarrant_key_dates, aes(x = key_date, y = Count, label = key_date), hjust = 0, vjust = 1.4)+
  ylim(-10000,700000)+
  ylab("Number of Cases and Deaths")+
  xlab("Date")+
  ggtitle("Tarrant County Covid-19 Case and Death Counts")+
  theme(plot.title = element_text(hjust = 0.5))+
    scale_color_manual(name = "Legend",
                       labels = c("Cases","Deaths"),
                       values = c(Cases="blue",Deaths="red"))
})
chart1
```

Let's look at percent of total population in recovered, deaths, uninfected, active
```{r SIR Chart}
chart2 <- ggplot(data = us_data_comb)+
  geom_area(aes(x = final_date, y = uninfected, color = "uninfected", fill = "uninfected"))+
  geom_area(aes(x = final_date, y = recovered, color = "recovered", fill = "recovered"))+
  geom_area(aes(x = final_date, y = active, color = "active", fill = "active"))+
  geom_area(aes(x = final_date, y = deaths, color = "deaths", fill ="deaths"))+
  scale_color_manual(name='Legend',
                     labels = c("Active","Deaths","Recovered","Uninfected"),
                     values=c(uninfected="black", recovered="darkgreen", active="darkblue", deaths="red"))+
  scale_fill_manual(name='Legend',
                    labels = c("Active","Deaths","Recovered","Uninfected"),
                     values=c(uninfected="black", recovered="darkgreen", active="darkblue", deaths="red"))+
  ylim(0,332000000)+
  xlab("Date (2020-01-22 to 2023-03-09)")+
  ylab("")+
  theme_minimal()+
  ggtitle("US Disease Status Over Time")+
  theme(plot.title = element_text(hjust = .5))

chart2
```


```{r}
Chart3 <- ggplot(data = us_data_comb_Rt[8:nrow(us_data_comb_Rt),])+
  geom_line(aes(x = final_date, y = `Mean(R)`))+
  xlab("Date (2020-04-27 to 2023-03-09)")+
  theme_minimal()+
    ggtitle(expression(paste("United States ",R["t"]," over Time",sep = "")))+
  theme(plot.title = element_text(hjust = .5))

Chart3
```


## Analysis: 

```{r}

```

